# -*- coding: utf-8 -*-
"""Wheather_Project by Shruti Mehra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gZOaSDUJ4HvfM_SYcXUFU8D3fifINMLO
"""

import requests

from datetime import datetime

api_key = '2d9a90249651b23bde8638736d0365a2'
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()


temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")
r=requests.get("https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key)
with open('wheather.text','wb') as f:
    f.write(r.content)



print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')